return {
  --  {
  --    "lukas-reineke/indent-blankline.nvim",
  --    main = "ibl",
  --    opts = {
  --      indent = {
  --        char = '├',
  --        tab_char = '',
  --        highlight = "ColorColumn"
  --      },
  --      scope = {
  --        enabled = true,
  --        highlight = "NonText"
  --      }
  --    },
  --    config = function(_, opts)
  --      require("ibl").setup(opts)

  --      local hooks = require "ibl.hooks"
  --      hooks.register(hooks.type.SCOPE_HIGHLIGHT, hooks.builtin.scope_highlight_from_extmark)
  --      hooks.register(
  --        hooks.type.WHITESPACE,
  --        hooks.builtin.hide_first_space_indent_level
  --      )
  --    end
  --  },

  -- {
  --   'echasnovski/mini.indentscope',
  --   config = function()
  --     require('mini.indentscope').setup({
  --       options = {
  --         indent_at_cursor = false,
  --         try_as_border = true,
  --       },
  --       symbol = '├',
  --     })
  --     vim.api.nvim_set_hl(0, 'MiniIndentscopeSymbol', { link = "VertSplit" })
  --   end
  -- },
}
