return {
  -- {
  --   "nvim-telescope/telescope.nvim",
  --   dependencies = {
  --     "nvim-lua/plenary.nvim",
  --     { "nvim-telescope/telescope-fzf-native.nvim", build = "make" },
  --     "nvim-telescope/telescope-ui-select.nvim",
  --     "debugloop/telescope-undo.nvim",
  --   },
  --   config = function()
  --     require("telescope").setup({
  --       defaults = {
  --         border = true,
  --         borderchars = tools.ui.cur_border,
  --         file_ignore_patterns = {
  --           "%.DS_Store",
  --           "%.jpeg",
  --           "%.jpg",
  --           "%.otf",
  --           "%.png",
  --           "%.ttf",
  --           "^.git/.*$",
  --           "^.yarn/",
  --           "^node_modules/",
  --           "^site-packages/",
  --         },
  --         layout_strategy = "bottom_pane",
  --         layout_config = {
  --           prompt_position = "top",
  --           height = 30,
  --           vertical = {
  --             width = 0.9,
  --             height = 0.95,
  --             preview_height = 0.75,
  --           },
  --         },
  --         sorting_strategy = "ascending",
  --       },
  --       extensions = {
  --         fzf = {
  --           fuzzy = true,
  --           override_generic_sorter = true,
  --           override_file_sorter = true,
  --           case_mode = "smart_case",
  --         },
  --         undo = {
  --           diff_context_lines = 20,
  --           layout_strategy = "vertical",
  --           mappings = {
  --             i = {
  --               ["<cr>"] = require("telescope-undo.actions").restore,
  --               ["<C-cr>"] = require("telescope-undo.actions").yank_additions,
  --               ["<S-cr>"] = require("telescope-undo.actions").yank_deletions,
  --             },
  --           },
  --         },
  --       },
  --       pickers = {
  --         buffers = {
  --           ignore_current_buffer = true,
  --           show_all_buffers = true,
  --           sort_lastused = true,
  --           sort_mru = true,
  --           mappings = {
  --             i = {
  --               ["<c-d>"] = "delete_buffer",
  --             },
  --             n = {
  --               ["<c-d>"] = "delete_buffer",
  --             }
  --           }
  --         },
  --         find_files = {
  --           hidden = true
  --         },
  --       },
  --     })
  --
  --     require("telescope").load_extension("fzf")
  --     require("telescope").load_extension("ui-select")
  --     require("telescope").load_extension("undo")
  --
  --     local builtin = require("telescope.builtin")
  --     local cmd = vim.api.nvim_create_user_command
  --
  --     cmd("Highlights", function() builtin.highlights() end, {})
  --     cmd("Keymaps", function() builtin.keymaps() end, {})
  --     cmd("PrevSearch", function() builtin.pickers() end, {})
  --
  --     vim.api.nvim_set_hl(0, "TelescopeNormal", { link = "NormalFloat" })
  --
  --     vim.keymap.set("n", "<C-t>", function()
  --       builtin.find_files({ hidden = true })
  --     end, { silent = true })
  --     vim.keymap.set("n", "<C-q>", builtin.quickfix, { silent = true })
  --     vim.keymap.set("n", "\\", builtin.buffers, { silent = false })
  --     vim.keymap.set("n", "<C-f>", builtin.live_grep, { silent = true })
  --
  --     -- LSP
  --     vim.keymap.set("n", "<leader>D", builtin.lsp_definitions, { silent = true })
  --     vim.keymap.set("n", "<leader>I", builtin.lsp_implementations, { silent = true })
  --     vim.keymap.set("n", "<leader>R", builtin.lsp_references, { silent = true })
  --     vim.keymap.set("n", "<leader>IC", builtin.lsp_incoming_calls, { silent = true })
  --     vim.keymap.set("n", "<leader>OC", builtin.lsp_outgoing_calls, { silent = true })
  --
  --     -- git
  --     vim.keymap.set("n", "<leader>GC", function()
  --       builtin.git_commits({
  --         layout_strategy = "vertical"
  --       })
  --     end, { silent = true })
  --     vim.keymap.set("n", "<leader>GB", builtin.git_branches, { silent = true })
  --
  --     vim.keymap.set("n", "<leader>u", "<cmd>Telescope undo<cr>", { silent = true })
  --   end
  -- },
}
